### ISSUE TITLE
How does this compare to Google Workbox?

### ISSUE THREAD

**Issue by nickchomey** [thepassle/swtl#5]
I just stumbled upon this while looking for a lightweight js template engine for use in a service worker. It looks great!

My question is given that this has routing, caching strategies etc..., how does it compare to the well-developed Google Workbox library? Workbox has modules for routing, caching strategies, streaming and more. 

So, is it mainly just the fact that swtl has template rendering? 

Thanks!

**Comment by thepassle** [comment]
I wouldnt necessarily position SWTL as a competitor to Workbox, Workbox is a great toolkit for developing anything service worker related. (Although Workbox sadly seems to have been abandoned by google for some reason :( )

While you can achieve streaming/"template stitching" with workbox (see https://jeffy.info/2021/07/17/sw-rendering.html), it doesnt offer declarative/component-like templating, like SWTL does. 

SWTL ships a router because I needed a simple one and want to use [URLPattern](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern).

Im generally very careful not to position SWTL as "the next big thing" or a competitor to anything. SWTL really is just a side project that I think is cool, and I built because it seemed like a fun/cool thing to work on. 

> So, is it mainly just the fact that swtl has template rendering?

So in short: Yes 😄

**Comment by thepassle** [comment]
> And sorry for framing it sort of as a competition - that wasn't intended

No worries, all good! I just try to be (maybe overly) cautious with that sort of thing :)

> On that note, do you intend to keep developing it for something that is in production, or is it really just a true side hobby project?

I have a couple of projects (also at work) that use SWTL, as well as a couple of hobby projects that use SWTL. Having said that, I can't guarantee enterprise-like support or anything like that, since this is just FOSS and I work on this in my spare time. The nice thing about small libraries like SWTL however is that if it does at some point get abandoned, its easy enough to fork, because the logic is really very small and just some iteration over a string

> If I use SWTL, I'll be happy to provide PRs as they come up!

I'd be happy to review them! Also feel free to let me know if you run into any issues, and we can see how we can tackle them :)

**Comment by thepassle** [comment]
If its fine by you I'll close this issue now :)
